Use isPresent() instead of isElementPresent()
Because those two specs are failing on CircleCI with the following
message:
Error: SubLocator is not supplied as a parameter to
`isElementPresent(subLocator)`. You are probably looking for the
function `isPresent()`.